import { useState } from "react";

export default function DataStore() {
    const [markers, setMarkers] = useState([
        { id: 1, 
            pos: {lat: 52.50267360154913, lng:  13.384722858800526},
            img: 'death',
            title: 'Adolf Hitler\'s Death',
            date: '30 April, 1945',
            year: 1945,
            desc: 'Adolf Hitler, infamous Nazi leader, died by suicide in April 1945 as World War II neared its end. In his Berlin bunker, facing defeat by advancing Allied forces, he ingested poison and shot himself. Hitler\'s death marked a turning point, leading to Germany\'s surrender and the collapse of the Nazi regime that had caused widespread devastation.',
            wiki: 'https://en.wikipedia.org/wiki/Death_of_Adolf_Hitler', 
            isOpen: false,
        },
        { id: 2, 
            pos: {lat: 38.89673159137992, lng:  -77.0265033031597},
            img: 'death',
            title: 'Death of Abraham Lincoln',
            date: '15 April, 1865',
            year: 1865,
            desc: 'Abraham Lincoln, 16th U.S. President, was assassinated in April 1865 at Ford\'s Theatre in Washington, D.C. Shot by John Wilkes Booth, a Confederate sympathizer, Lincoln died the following day. His assassination occurred just days after the Civil War\'s end. Lincoln\'s death had a profound impact on post-war America, altering the course of Reconstruction and leaving an enduring legacy.',
            wiki: 'https://en.wikipedia.org/wiki/Assassination_of_Abraham_Lincoln', 
            isOpen: false,
        },
        { id: 3, 
            pos: {lat: 32.778872496346516, lng:  -96.8085997107288},
            img: 'death',
            title: 'Death of John F. Kennedy',
            date: '22 November, 1963',
            year: 1963,
            desc: 'John F. Kennedy, 35th U.S. President, was assassinated in November 1963 in Dallas, Texas. While riding in a motorcade, he was fatally shot by Lee Harvey Oswald. Kennedy\'s assassination shocked the nation and the world, leading to investigations and conspiracy theories. His death marked a pivotal moment in American history, impacting politics, culture, and perceptions of leadership.',
            wiki: 'https://en.wikipedia.org/wiki/Assassination_of_John_F._Kennedy', 
            isOpen: false,
        },
        { id: 4, 
            pos: {lat: 43.85774387538882,  lng:  18.428679260834024},
            img: 'death',
            title: 'Death of Archduke Ferdinand of Austria',
            date: '28 June, 1914',
            year: 1914,
            desc: 'Archduke Franz Ferdinand of Austria, heir to the Austro-Hungarian throne, was assassinated in June 1914 in Sarajevo, Bosnia. Gavrilo Princip, a Serbian nationalist, shot him and his wife. This event triggered a series of alliances and tensions, ultimately sparking World War I. The assassination is considered a catalyst for the conflict that reshaped global politics and society.',
            wiki: 'https://en.wikipedia.org/wiki/Assassination_of_Archduke_Franz_Ferdinand', 
            isOpen: false,
            },
            { id: 5, 
            pos: {lat: 35.13436972891019,  lng:  -90.0581120259952},
            img: 'death',
            title: 'Death of Martin Luther King Jr.',
            date: '4 April, 1968',
            year: 1968,
            desc: 'Dr. Martin Luther King Jr., a prominent civil rights leader, was assassinated in April 1968 in Memphis, Tennessee. Shot by James Earl Ray, his death occurred while he was advocating for equality and justice for African Americans. King\'s assassination led to widespread mourning and ignited riots in some cities. His legacy lives on as a symbol of the fight against racial discrimination and the pursuit of civil rights in the United States.',
            wiki: 'https://en.wikipedia.org/wiki/Assassination_of_Martin_Luther_King_Jr.', 
            isOpen: false,
            },
            { id: 6, 
            pos: {lat: 55.75012458198545,  lng:  37.40611518651629},
            img: 'death',
            title: 'Death of Joseph Stalin',
            date: '5 March, 1953',
            year: 1953,
            desc: 'Joseph Stalin, Soviet leader, died in March 1953. His death resulted from a stroke, ending his long and oppressive rule. Stalin\'s leadership was marked by political purges, collectivization, and mass repression, causing immense suffering and death. His passing led to a period of uncertainty and eventual changes in the Soviet Union\'s leadership and policies.',
            wiki: 'https://en.wikipedia.org/wiki/The_Death_of_Stalin', 
            isOpen: false,
            },
            { id: 7, 
            pos: {lat: 39.8135, lng:  -77.2325},
            img: 'cultural',
            title: 'Battle of Gettysburg',
            date: '1-3 July, 1863',
            year: 1863,
            desc: 'The Battle of Gettysburg was a turning point in the American Civil War, fought from July 1 to 3, 1863, in Pennsylvania. It marked the Union victory over the Confederate forces led by General Robert E. Lee. The battle is known for its immense casualties and its significance in shaping the war\'s outcome.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 8, 
            pos: {lat: -18.906519877130052, lng:  -52.984371304197275},
            img: 'birth',
            title: 'Battle of Waterloo',
            date: '18 June, 1825',
            year: 1825,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 9, 
            pos: {lat: -14.906519877130052, lng:  -57.984371304197275},
            img: 'cultural',
            title: 'Battle of Waterloo',
            date: '18 June, 1835',
            year: 1835,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 10, 
            pos: {lat: -18.906519877130052, lng:  -52.984371304197275},
            img: 'birth',
            title: 'Battle of Waterloo',
            date: '18 June, 1825',
            year: 1825,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 11, 
                pos: {lat: -13.906519877130052, lng:  -59.984371304197275},
                img: 'battle',
                title: 'Battle of Waterloo',
                date: '18 June, 1815',
                year: 1815,
                desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
                wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
                isOpen: false,
            },
            { id: 12, 
                pos: {lat: -14.906519877130052, lng:  -57.984371304197275},
                img: 'cultural',
                title: 'Battle of Waterloo',
                date: '18 June, 1835',
                year: 1835,
                desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
                wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
                isOpen: false,
            },
            { id: 13, 
                pos: {lat: -18.906519877130052, lng:  -52.984371304197275},
                img: 'birth',
                title: 'Battle of Waterloo',
                date: '18 June, 1825',
                year: 1825,
                desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
                wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
                isOpen: false,
            },
            { id: 14, 
            pos: {lat: -14.906519877130052, lng:  -57.984371304197275},
            img: 'cultural',
            title: 'Battle of Waterloo',
            date: '18 June, 1835',
            year: 1835,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 15, 
            pos: {lat: -18.906519877130052, lng:  -52.984371304197275},
            img: 'birth',
            title: 'Battle of Waterloo',
            date: '18 June, 1825',
            year: 1825,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 16, 
            pos: {lat: -13.906519877130052, lng:  -59.984371304197275},
            img: 'battle',
            title: 'Battle of Waterloo',
            date: '18 June, 1815',
            year: 1815,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 17, 
            pos: {lat: -14.906519877130052, lng:  -57.984371304197275},
            img: 'cultural',
            title: 'Battle of Waterloo',
            date: '18 June, 1835',
            year: 1835,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 18, 
            pos: {lat: -18.906519877130052, lng:  -52.984371304197275},
            img: 'birth',
            title: 'Battle of Waterloo',
            date: '18 June, 1825',
            year: 1825,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 19, 
            pos: {lat: -14.906519877130052, lng:  -57.984371304197275},
            img: 'cultural',
            title: 'Battle of Waterloo',
            date: '18 June, 1835',
            year: 1835,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 20, 
            pos: {lat: -18.906519877130052, lng:  -52.984371304197275},
            img: 'birth',
            title: 'Battle of Waterloo',
            date: '18 June, 1825',
            year: 1825,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 21, 
                pos: {lat: -13.906519877130052, lng:  -59.984371304197275},
                img: 'battle',
                title: 'Battle of Waterloo',
                date: '18 June, 1815',
                year: 1815,
                desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
                wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
                isOpen: false,
            },
            { id: 22, 
                pos: {lat: -14.906519877130052, lng:  -57.984371304197275},
                img: 'cultural',
                title: 'Battle of Waterloo',
                date: '18 June, 1835',
                year: 1835,
                desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
                wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
                isOpen: false,
            },
            { id: 23, 
                pos: {lat: -18.906519877130052, lng:  -52.984371304197275},
                img: 'birth',
                title: 'Battle of Waterloo',
                date: '18 June, 1825',
                year: 1825,
                desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
                wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
                isOpen: false,
            },
            { id: 24, 
            pos: {lat: -14.906519877130052, lng:  -57.984371304197275},
            img: 'cultural',
            title: 'Battle of Waterloo',
            date: '18 June, 1835',
            year: 1835,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 25, 
            pos: {lat: -18.906519877130052, lng:  -52.984371304197275},
            img: 'birth',
            title: 'Battle of Waterloo',
            date: '18 June, 1825',
            year: 1825,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 26, 
            pos: {lat: -13.906519877130052, lng:  -59.984371304197275},
            img: 'battle',
            title: 'Battle of Waterloo',
            date: '18 June, 1815',
            year: 1815,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 27, 
            pos: {lat: -14.906519877130052, lng:  -57.984371304197275},
            img: 'cultural',
            title: 'Battle of Waterloo',
            date: '18 June, 1835',
            year: 1835,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 28, 
            pos: {lat: -18.906519877130052, lng:  -52.984371304197275},
            img: 'birth',
            title: 'Battle of Waterloo',
            date: '18 June, 1825',
            year: 1825,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 29, 
            pos: {lat: -14.906519877130052, lng:  -57.984371304197275},
            img: 'cultural',
            title: 'Battle of Waterloo',
            date: '18 June, 1835',
            year: 1835,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 30, 
            pos: {lat: -18.906519877130052, lng:  -52.984371304197275},
            img: 'birth',
            title: 'Battle of Waterloo',
            date: '18 June, 1825',
            year: 1825,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 31, 
                pos: {lat: -13.906519877130052, lng:  -59.984371304197275},
                img: 'battle',
                title: 'Battle of Waterloo',
                date: '18 June, 1815',
                year: 1815,
                desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
                wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
                isOpen: false,
            },
            { id: 32, 
                pos: {lat: -14.906519877130052, lng:  -57.984371304197275},
                img: 'cultural',
                title: 'Battle of Waterloo',
                date: '18 June, 1835',
                year: 1835,
                desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
                wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
                isOpen: false,
            },
            { id: 33, 
                pos: {lat: -18.906519877130052, lng:  -52.984371304197275},
                img: 'birth',
                title: 'Battle of Waterloo',
                date: '18 June, 1825',
                year: 1825,
                desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
                wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
                isOpen: false,
            },
            { id: 34, 
            pos: {lat: -14.906519877130052, lng:  -57.984371304197275},
            img: 'cultural',
            title: 'Battle of Waterloo',
            date: '18 June, 1835',
            year: 1835,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 35, 
            pos: {lat: -18.906519877130052, lng:  -52.984371304197275},
            img: 'birth',
            title: 'Battle of Waterloo',
            date: '18 June, 1825',
            year: 1825,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 36, 
            pos: {lat: -13.906519877130052, lng:  -59.984371304197275},
            img: 'battle',
            title: 'Battle of Waterloo',
            date: '18 June, 1815',
            year: 1815,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 37, 
            pos: {lat: -14.906519877130052, lng:  -57.984371304197275},
            img: 'cultural',
            title: 'Battle of Waterloo',
            date: '18 June, 1835',
            year: 1835,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 38, 
            pos: {lat: -18.906519877130052, lng:  -52.984371304197275},
            img: 'birth',
            title: 'Battle of Waterloo',
            date: '18 June, 1825',
            year: 1825,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 39, 
            pos: {lat: -14.906519877130052, lng:  -57.984371304197275},
            img: 'cultural',
            title: 'Battle of Waterloo',
            date: '18 June, 1835',
            year: 1835,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
            { id: 40, 
            pos: {lat: -18.906519877130052, lng:  -52.984371304197275},
            img: 'birth',
            title: 'Battle of Waterloo',
            date: '18 June, 1825',
            year: 1825,
            desc: 'The Battle of Waterloo, fought on June 18, 1815, was a pivotal event in European history that marked the end of the Napoleonic era and Napoleon Bonaparte\'s military ambitions. It took place near the town of Waterloo in present-day Belgium. The battle was a culmination of Napoleon\'s attempt to regain power after his earlier exile to the island of Elba.',
            wiki: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo', 
            isOpen: false,
            },
      ]);

      return markers;
}